name: Sync production to main

on:
  push:
    branches:
      - production

jobs:
  sync-production-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset branch
        run: |
          git fetch origin production:production
          git reset --hard production

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore: sync production to main'
          title: 'Sync production to main'
          body: 'Automated PR to sync `production` branch to `main` branch'
          branch: sync-production-to-main
          base: main
          labels: |
            automated
            sync

      - name: Enable auto-merge
        run: |
          pr_url=$(gh pr list --head sync-production-to-main --base main --json url -q '.[0].url')
          gh pr merge "$pr_url" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
